approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.0.cjs
npmPreapprovedPackages:
  - vitest
  - '@vitest/*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.979ed9ea6778e184fb4d9c19a8a8df4c015c901c
  vite-plus: 0.0.0-commit.979ed9ea6778e184fb4d9c19a8a8df4c015c901c
npmRegistryServer: https://registry-bridge.viteplus.dev/
